# R Programming Basic Task 2
Date: Nov 10, 2020

### 1. Object x <-1:15
 Construct a 5x3 matrix for the value of x.
 
 A matrix is a two-dimensional rectangular data set. It can be created using a vector input to the matrix function.

In [1]:
x <- 1:15
m <- matrix(x, nrow = 5, ncol = 3, byrow = TRUE)
m

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12  
[5,] 13   14   15

### 2. Write a program to generate the following 4x4 matrix
 0 0 0 0
 
 0 0 0 0
 
 0 0 0 0
 
 0 0 0 0
 
 All the value of the matrix = 0, so we can put 0 as the value of matrix in matrix() function directly. 

In [2]:
m <- matrix(0, nrow = 4, ncol = 4, byrow = TRUE) 
m

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

### 3. The object x<-1:8
 Write a program to generate the following 3x8 matrix using "cbind(),rbind(),rev(),rep()"
 
 1 2 3 4 5 6 7 8
 
 8 7 6 5 4 3 2 1
 
 3 3 3 3 3 3 3 3
 
 **cbind()**: Combine vectors as columns in a matrix.
 
 **rbind()**: Combine vectors as rows in a matrix.
 
 **rev()**: used to return the reverse version of data objects.
 
 **rep()**: replicates the values of elements/vectors.

In [3]:
x <- 1:8
rbind(unname(x), rev(x), rep(3))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3    4    5    6    7    8   
[2,] 8    7    6    5    4    3    2    1   
[3,] 3    3    3    3    3    3    3    3

### 4. Chose two different(x,y) 4x4 matrix to perform the following arithmetic operations
    (a). x + y
    (b). x - y
    (c). x*y
    (d). x%*%y
    (e). Difference between (c) &(d)
    (f). Inverse of y
    (g). z<-x/y
    (h). Transpose of z
    (i). Diagonal of transpose matrix

In [4]:
x <- matrix(1:16, 4, 4, TRUE)
y <- matrix(c(1,8,4,2,4,5,5,1,2,2,5,4,4,1,1,2), 4, 4)

x
y

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[,1] [,2] [,3] [,4]
[1,] 1    4    2    4   
[2,] 8    5    2    1   
[3,] 4    5    5    1   
[4,] 2    1    4    2

In [5]:
#(a) adding matrices is the same as adding two elements in each other

x + y

[,1] [,2] [,3] [,4]
[1,]  2    6    5    8  
[2,] 13   11    9    9  
[3,] 13   15   16   13  
[4,] 15   15   19   18

In [6]:
#(b) perform subtraction operation on two matrices 

x - y

[,1] [,2] [,3] [,4]
[1,]  0   -2    1    0  
[2,] -3    1    5    7  
[3,]  5    5    6   11  
[4,] 11   13   11   14

In [7]:
#(c) Element-wise multiplication: the elements in the same row are multiplied by one another.

x * y

[,1] [,2] [,3] [,4]
[1,]  1    8    6   16  
[2,] 40   30   14    8  
[3,] 36   50   55   12  
[4,] 26   14   60   32

In [8]:
#(d) Matrix multiplication

x %*% y

[,1] [,2] [,3] [,4]
[1,]  37   33   37   17 
[2,]  97   93   89   49 
[3,] 157  153  141   81 
[4,] 217  213  193  113

    (e). Difference between (c) &(d)
In **(c) Element-wise multiplication**:  used for multiplying a matrix by scalar or element-wise multiplication of two matrices.

In **(d) Matrix multiplcation(%*%)**: satisfying the condition that the number of columns in the first matrix is equal to the number of rows in second. If matrix A[M, N] and matrix B[N, Z] are multiplied then the resultant matrix will of dimension M*N.

    (f) The inverse of a matrix can be calculated in R with the help of solve() function, not inv() function. The function solve is giving an error if only if the inverse of a non-square matrix cannot be calculated. Although it is a square matrix but sometimes even the inverse of a square does not exist.

In [9]:
#(f) Inverse of a matrix

solve(y)

[,1]        [,2]        [,3]       [,4]      
[1,] -0.07086614  0.17322835 -0.1417323  0.1259843
[2,]  0.11023622 -0.04724409  0.2204724 -0.3070866
[3,] -0.09448819 -0.10236220  0.1443570  0.1679790
[4,]  0.20472441  0.05511811 -0.2572178  0.1916010

In [10]:
#(g) The elements in the same row of one matrix are divided by one another.

z <- x/y
z

[,1]  [,2] [,3] [,4]
[1,] 1.000  0.5 1.50  1  
[2,] 0.625  1.2 3.50  8  
[3,] 2.250  2.0 2.20 12  
[4,] 6.500 14.0 3.75  8

In [11]:
#(h) Transpose of z: another matrix with the rows and columns interchanged.

t(z)

[,1] [,2]  [,3]  [,4] 
[1,] 1.0  0.625  2.25  6.50
[2,] 0.5  1.200  2.00 14.00
[3,] 1.5  3.500  2.20  3.75
[4,] 1.0  8.000 12.00  8.00

In [12]:
#(i) Diagonal of transpose matrix: 
# Function daig() used to retrieve the elements along the principal diagonal of a matrix.
# Even for non-square matrices, the diag() function returns the diagonal starting from elements [1,1], [2,2], ... till no such elements can be retrieved.

diag(z)

[1] 1.0 1.2 2.2 8.0

### 5. Difference between (i) & (ii)
     (i). x<-matrix(x<-1:9,3,3,byrow = TRUE) 
     (ii). x<-matrix(x<-1:9,3,3)
     
**byrow=TRUE** indicates that the matrix should be filled by rows. 

**byrow=FALSE** indicates that the matrix should be filled by columns (the default).

So the different between (i) and (ii) is because of **byrow = TRUE**. (i) will return matrix which filled by row one value by one value. (ii) will return matrix which filled by column one value by one value.

In [13]:
x<-matrix(x<-1:9, 3, 3, byrow = TRUE) 
x

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [14]:
x <- matrix(x<-1:9, 3, 3)
x

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

### 6. Which function can we use for inner product and outer product in matrix calculation?
+ For inner product, in R there is no function particularly, but we can use inner arithmetic operator %*% directly.
+ For outer product, we can either use outer arithmetic operator %o% or use outer() function.

In [1]:
x <- 1:4
y <- diag(x)
z <- matrix(1:16, 4, 4, TRUE)

y %*% z     # Inner product

y %o% z     # Outer product

outer(y, z) # Outer product

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,] 10   12   14   16  
[3,] 27   30   33   36  
[4,] 52   56   60   64

, , 1, 1

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    2    0    0
[3,]    0    0    3    0
[4,]    0    0    0    4

, , 2, 1

     [,1] [,2] [,3] [,4]
[1,]    5    0    0    0
[2,]    0   10    0    0
[3,]    0    0   15    0
[4,]    0    0    0   20

, , 3, 1

     [,1] [,2] [,3] [,4]
[1,]    9    0    0    0
[2,]    0   18    0    0
[3,]    0    0   27    0
[4,]    0    0    0   36

, , 4, 1

     [,1] [,2] [,3] [,4]
[1,]   13    0    0    0
[2,]    0   26    0    0
[3,]    0    0   39    0
[4,]    0    0    0   52

, , 1, 2

     [,1] [,2] [,3] [,4]
[1,]    2    0    0    0
[2,]    0    4    0    0
[3,]    0    0    6    0
[4,]    0    0    0    8

, , 2, 2

     [,1] [,2] [,3] [,4]
[1,]    6    0    0    0
[2,]    0   12    0    0
[3,]    0    0   18    0
[4,]    0    0    0   24

, , 3, 2

     [,1] [,2] [,3] [,4]
[1,]   10    0    0    0
[2,]    0   20    0    0
[3,]    0    0   30    0
[4,]    0    0    0   40

, , 4, 2

     [,1] [,2] [,3] [,4]
[1,]   14    0    0    0
[2,]    0   28    0    0
[3,]    0    0   42    0
[4,]    0    0    0   56

, , 1, 3

     [,1] [,2] [,3] [,4]
[1,]    3    0    0    0
[2,]    0    6    0    0
[3,]    0    0    9    0
[4,]    0    0    0   12

, , 2, 3

     [,1] [,2] [,3] [,4]
[1,]    7    0    0    0
[2,]    0   14    0    0
[3,]    0    0   21    0
[4,]    0    0    0   28

, , 3, 3

     [,1] [,2] [,3] [,4]
[1,]   11    0    0    0
[2,]    0   22    0    0
[3,]    0    0   33    0
[4,]    0    0    0   44

, , 4, 3

     [,1] [,2] [,3] [,4]
[1,]   15    0    0    0
[2,]    0   30    0    0
[3,]    0    0   45    0
[4,]    0    0    0   60

, , 1, 4

     [,1] [,2] [,3] [,4]
[1,]    4    0    0    0
[2,]    0    8    0    0
[3,]    0    0   12    0
[4,]    0    0    0   16

, , 2, 4

     [,1] [,2] [,3] [,4]
[1,]    8    0    0    0
[2,]    0   16    0    0
[3,]    0    0   24    0
[4,]    0    0    0   32

, , 3, 4

     [,1] [,2] [,3] [,4]
[1,]   12    0    0    0
[2,]    0   24    0    0
[3,]    0    0   36    0
[4,]    0    0    0   48

, , 4, 4

     [,1] [,2] [,3] [,4]
[1,]   16    0    0    0
[2,]    0   32    0    0
[3,]    0    0   48    0
[4,]    0    0    0   64

, , 1, 1

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    2    0    0
[3,]    0    0    3    0
[4,]    0    0    0    4

, , 2, 1

     [,1] [,2] [,3] [,4]
[1,]    5    0    0    0
[2,]    0   10    0    0
[3,]    0    0   15    0
[4,]    0    0    0   20

, , 3, 1

     [,1] [,2] [,3] [,4]
[1,]    9    0    0    0
[2,]    0   18    0    0
[3,]    0    0   27    0
[4,]    0    0    0   36

, , 4, 1

     [,1] [,2] [,3] [,4]
[1,]   13    0    0    0
[2,]    0   26    0    0
[3,]    0    0   39    0
[4,]    0    0    0   52

, , 1, 2

     [,1] [,2] [,3] [,4]
[1,]    2    0    0    0
[2,]    0    4    0    0
[3,]    0    0    6    0
[4,]    0    0    0    8

, , 2, 2

     [,1] [,2] [,3] [,4]
[1,]    6    0    0    0
[2,]    0   12    0    0
[3,]    0    0   18    0
[4,]    0    0    0   24

, , 3, 2

     [,1] [,2] [,3] [,4]
[1,]   10    0    0    0
[2,]    0   20    0    0
[3,]    0    0   30    0
[4,]    0    0    0   40

, , 4, 2

     [,1] [,2] [,3] [,4]
[1,]   14    0    0    0
[2,]    0   28    0    0
[3,]    0    0   42    0
[4,]    0    0    0   56

, , 1, 3

     [,1] [,2] [,3] [,4]
[1,]    3    0    0    0
[2,]    0    6    0    0
[3,]    0    0    9    0
[4,]    0    0    0   12

, , 2, 3

     [,1] [,2] [,3] [,4]
[1,]    7    0    0    0
[2,]    0   14    0    0
[3,]    0    0   21    0
[4,]    0    0    0   28

, , 3, 3

     [,1] [,2] [,3] [,4]
[1,]   11    0    0    0
[2,]    0   22    0    0
[3,]    0    0   33    0
[4,]    0    0    0   44

, , 4, 3

     [,1] [,2] [,3] [,4]
[1,]   15    0    0    0
[2,]    0   30    0    0
[3,]    0    0   45    0
[4,]    0    0    0   60

, , 1, 4

     [,1] [,2] [,3] [,4]
[1,]    4    0    0    0
[2,]    0    8    0    0
[3,]    0    0   12    0
[4,]    0    0    0   16

, , 2, 4

     [,1] [,2] [,3] [,4]
[1,]    8    0    0    0
[2,]    0   16    0    0
[3,]    0    0   24    0
[4,]    0    0    0   32

, , 3, 4

     [,1] [,2] [,3] [,4]
[1,]   12    0    0    0
[2,]    0   24    0    0
[3,]    0    0   36    0
[4,]    0    0    0   48

, , 4, 4

     [,1] [,2] [,3] [,4]
[1,]   16    0    0    0
[2,]    0   32    0    0
[3,]    0    0   48    0
[4,]    0    0    0   64

### 7. Explain the use of all.equal() function in Matrix with a sample program.
all.equal(x, y) is a utility to compare R objects x and y testing ‘near equality’. If they are different, comparison is still made to some extent, and a report of the differences is returned.

In [16]:
a <- matrix(1:16, ncol = 4)
b <- matrix(1:16, ncol = 4)
c <- matrix(1:16, ncol = 2)

all.equal(a, b) # Return TRUE, because value and dimensions are the same
all.equal(a, c) # FALSE, because the dimensions are different

[1] TRUE

[1] "Attributes: < Component \"dim\": Mean relative difference: 0.75 >"

### 8. Explain the use of dim() function with a sample program.
+ dim() function used to get or set the dimension of the specified matrix, array or data frame.
+ Syntax: dim(x)
+ x can be array, matrix or data frame.

In [17]:
num <- 1:20

# Set dimension of 4 * 5

dim(num) <- c(4,5)

num

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

### 9. Use of ($)operator, and square brackets [] in List with example program

+ Using the dollar sign ($) for subsetting the data if the elements are named.
+ Using the square brackets [] for subsetting the data either the elements are named or not.

In [18]:
l <- list(6:12, 1:5, 2:8)

l[2]    # remark by put the list 1
l[[1]]  # no remark

[[1]]
[1] 1 2 3 4 5

[1]  6  7  8  9 10 11 12

In [19]:
# using $ operator to subset the list
# First we need to create the list.
# Then we give the names to the each elements by using names() function. 
# Last, call name element by using $ 

a <- 6:12
b <- 1:5
c <- 2:8
l <- list(a, b, c)
names(l) <- c("First", "Second", "Third")

l$Second

[1] 1 2 3 4 5

### 10. Explain ifelse() with example.
Syntax: ifelse(test_expression, x, y)
+ **test_expression** must be a logical vector or condition. The return value is a vector with the same length as test_expression.
+ This returned vector has element from x if the corresponding value of test_expression is **TRUE** or from y if the corresponding value of test_expression is **FALSE**.

In [20]:
a = c(4,12,5,8,0,2)
ifelse(a %% 2 == 0,"even","odd")

[1] "even" "even" "odd"  "even" "even" "even"

### 11. Write a program to get the weight and height from the user to calculate the following cases
    a. If your BMI is less than 18.5, it falls within the underweight range.
    b. If your BMI is 18.5 to <25, it falls within the normal.
    c. If your BMI is 25.0 to <30, it falls within the overweight range.
    d. If your BMI is 30.0 or higher, it falls within the obese range.

In [21]:
height <- as.numeric(readline(prompt = "Enter height(m): "))  
weight <- as.numeric(readline(prompt = "Enter weight(kg): "))  


bmi <- weight/(height ^ 2)
if(bmi < 18.5){
    print("Underweight range!")
} else if(bmi < 25) {
    print("Normal range!")
} else if(bmi < 30) {
    print("Overweight range!")
} else {
    print("Obses range!")
}

Enter height(m):  1.86
Enter weight(kg):  73


[1] "Normal range!"


### 12. Difference between List and Data frame with an example program.
List is an R-object which can contain many different types of elements inside it like vectors, functions and even another list inside it without any restriction on the class, length or structure of each element. You should not give two elements the same name. That might cause a lot of confusion, and R doesn't give errors for that:

In [22]:
# List
l <- list(c(1,2,3), 11.2, sin)
l

same_name <- list(age = 20, name = "Khean Sreythou", age = 21)
cat("Age return: ", same_name$age) # return age = 20

[[1]]
[1] 1 2 3

[[2]]
[1] 11.2

[[3]]
function (x)  .Primitive("sin")

Age return:  20

Data frame is tabular data objects. Each column can contain different type of data. 
+ Cannot use the same name for two different variables
+ all elements of a data frame are vectors
+ all elements of a data frame have an equal length.

In [23]:
student <- data.frame(
    roll_number = c(1101701001, 1101701002, 1101701003),
    name = c("Chhuny", "Munyvorn", "Nataly"),
    gender = c("Male", "Male", "Female"),
    age = c(21, 20, 22)
)

student

roll_number name     gender age
1 1101701001  Chhuny   Male   21 
2 1101701002  Munyvorn Male   20 
3 1101701003  Nataly   Female 22

#### 13. Difference between repeat and while loop with example program.
##### Repeat Loop
Used to iterate over a block of code multiple number of times. There is no condition check in repeat loop to exit the loop. We must put a condition explicitly inside the body of the loop and use the break statement to exit the loop. Failing to do so will result into an infinite loop.

Syntax: 

repeat  { 

statement 

}

In [24]:
x <- 1

repeat {
    cat("Hello World!\n")
    x <- x + 1
    if(x == 7){
        break
    }
}

Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!


##### while loop
Used to loop until a specific condition is met.

Syntax: 

while (test_expression) { 

statement

}

**test_expression** is evaluated and the body of the loop is entered if the result is TRUE. The statements inside the loop are executed and the flow returns to evaluate the test_expression again. This is repeated each time until **test_expression** evaluates to FALSE, in which case, the loop exits.

In [25]:
x <- 1

while(x < 7){
    cat("Hello World!\n")
    x <- x + 1
}

Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!


##### Different between repeat loop and while loop
**while loop** tests a condition to determine when to finish looping, but **repeat loop** requires you to explicitly break the loop on your own and can be at any point in the body of the loop. Depending on where you place your break statement, repeat may perform further parts of an iteration compared to while.